spring:
  datasource:
    reader:
      username: [ Master_Username ]
      password: [ your_password ]
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://your_reader_url:5432/productdb?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
      pattern: get*,find*
    writer:
      username: [ Master_Username ]
      password: [ your_password ]
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://your_writer_url:5432/productdb?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
      pattern: add*,update*
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8012
